Add additional Tls/SSL arguments
etianen/django-python3-ldap pull request #275
Opened 2024-06-13 13:11 UTC by Freddo3000

I'm running an LDAP server with a handful of old/legacy settings required, which causes this to fail to connect. Pullrequest adds support for entering those settings, and support for other unnamed options through keyword arguments.

2024-06-15 13:22 UTC, etianen requested changes
This looks good! I've made some doc suggestions for consistency, but otherwise looks great.

2024-06-15 13:22 UTC, etianen commented on README.rst
> +    # Specify which TLS ciphers to use
```suggestion
    # Specify which TLS ciphers to use.
```

2024-06-15 13:22 UTC, etianen commented on README.rst
> +    LDAP_AUTH_CONNECT_USE_SSL
```suggestion
    # Use SSL on the connection.
    LDAP_AUTH_CONNECT_USE_SSL = False
```

2024-06-15 13:22 UTC, etianen commented on README.rst
> +    LDAP_AUTH_TLS_ARGS = {}
```suggestion
    # Unspecified TLS keyword arguments applied to the connection on the underlying `ldap3` library.
    LDAP_AUTH_TLS_ARGS = {}
```

2024-06-15 13:22 UTC, etianen commented on README.rst
> +    LDAP_AUTH_CONNECT_ARGS = {}
```suggestion
    # Unspecified keyword arguments to apply to the connection in the underlying `ldap3` library.
    LDAP_AUTH_CONNECT_ARGS = {}
```

2024-06-15 13:23 UTC, etianen commented
I've allowed workflows for this PR so you can check linting and tests. You'll also need to resolve some conflicts on the readme.

Nice work though, so I'll be happy to merge this after these tweaks! ❤️

2024-06-15 13:26 UTC, Freddo3000 commented
> I've allowed workflows for this PR so you can check linting and tests. You'll also need to resolve some conflicts on the readme.
> 
> Nice work though, so I'll be happy to merge this after these tweaks! ❤️

Thanks! I've applied the changes now.

2024-07-29 18:55 UTC, etianen commented on README.rst
> +    LDAP_AUTH_TLS_VERSION = "ALL"
```suggestion
    LDAP_AUTH_TLS_CIPHERS = "ALL"
```

2024-07-29 18:56 UTC, merged

2024-07-29 18:57 UTC, etianen commented
Merged, and will shortly be released!
Apologies for the delay, I have been busy with a new baby!

2024-07-29 18:59 UTC, etianen commented
Published as 0.15.8